apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: keycloak
type: Opaque
stringData:
  # Keycloak Admin Console Credentials
  admin-username: "admin"
  admin-password: "StrongAdminPassword123!"

  # Database Credentials (used by both Postgres and Keycloak)
  db-username: "keycloak"
  db-password: "StrongDatabasePassword123!"