# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: keycloack
type: Opaque
stringData:
  admin-password: "StrongAdminPassword123!"
  postgres-password: "StrongDatabasePassword123!"
  password: "StrongDatabasePassword123!"