apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  image: quay.io/keycloak/keycloak:26.0.0

  # Database Connection
  db:
    vendor: postgres
    host: postgres-db
    port: 5432
    usernameSecret:
      name: keycloak-credentials
      key: db-username
    passwordSecret:
      name: keycloak-credentials
      key: db-password

  # Admin User (Bootstrap)
  # Essential for first access
  bootstrapAdmin:
    user:
      secret: keycloak-credentials

  hostname:
    hostname: auth.dmgiangi.dev

  http:
    tlsSecret: keycloak-ingress-tls

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: kong
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/preserve-host: "true"
      konghq.com/protocols: "https"
      konghq.com/proxy-buffer-size: "128k"