---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - home-pool
  interfaces:
    - eno1  # Primary network interface on calcifer-home node

