---
apiVersion: v1
kind: Namespace
metadata:
  name: kong
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
    vault-injection: enabled