---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kong-gateway
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/base/kong-gateway
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: metallb-config