apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/local-path-provisioner
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true