apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/terraform-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true