apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  interval: 5m
  chart:
    spec:
      chart: kong
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
      version: "2.x"
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    proxy:
      type: NodePort
      http:
        nodePort: 30080
      tls:
        nodePort: 30443
      externalTrafficPolicy: Cluster
    admin:
      type: ClusterIP
    ingressController:
      enabled: true
    replicaCount: 1