apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  interval: 5m
  chart:
    spec:
      chart: kong
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
      version: "2.x"
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    deployment:
      daemonset: true # <--- BEST PRACTICE: Uses DaemonSet to ensure Kong runs on every node (on single-node VPS).
      hostNetwork: true # <--- CRITICAL FIX 1: Enables the Pod to use the host's network stack (required for bare-metal exposure).
    containerSecurityContext:
      capabilities:
        add: [NET_BIND_SERVICE] # <--- CRITICAL FIX 2: Grants permission to bind to privileged ports (80/443).
        drop: []
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0 # <--- CRITICAL FIX 2: Runs the container as root to ensure necessary binding and volume permissions.
    proxy:
      type: ClusterIP # Service type remains ClusterIP, as the hostNetwork bypasses the need for NodePort/LoadBalancer for external exposure.
      http:
        containerPort: 80
        enabled: true
      tls:
        containerPort: 443
        enabled: true
      externalTrafficPolicy: Cluster
    admin:
      type: ClusterIP
    ingressController:
      enabled: true
