apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  interval: 5m
  chart:
    spec:
      chart: kong
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
      version: "2.x"
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    hostNetwork: true
    proxy:
      type: ClusterIP
      http:
        containerPort: 80
      tls:
        containerPort: 443
      externalTrafficPolicy: Cluster
    admin:
      type: ClusterIP
    ingressController:
      enabled: true
    replicaCount: 1