---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-infra
  namespace: flux-system
spec:
  interval: 5m

  path: ./infrastructure/controllers

  sourceRef:
    kind: GitRepository
    name: flux-system

  prune: true

  dependsOn:
    - name: flux-system