apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault
spec:
  size: 2
  image: hashicorp/vault:1.15.2

  # Service Account
  serviceAccount: vault

  # Azure Webhook Label
  vaultLabels:
    azure.workload.identity/use: "true"

  # Azure Unseal
  unsealConfig:
    azure:
      keyVaultName: "kv-calcifer-westeurope"

  # Physical Storage
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "local-path"
        resources:
          requests:
            storage: 5Gi

  #Mount Storage
  vaultContainerSpec:
    name: vault
    env:
      - name: SKIP_SETCAP
        value: "true"
      - name: SKIP_CHOWN
        value: "true"
    args:
      - "server"
      - "-config=/vault/config/vault.json"
    volumeMounts:
      - name: data
        mountPath: /vault/data
      - name: vault-config
        mountPath: /vault/config

  # internal config
  config:
    storage:
      raft:
        path: "/vault/data"
    listener:
      tcp:
        address: "0.0.0.0:8202"
        cluster_address: "0.0.0.0:8201"
        tls_disable: true
    ui: true
    disable_mlock: true
    api_addr: "http://vault.vault:8202"
    cluster_addr: "http://$(HOSTNAME).vault-internal:8201"

  vaultPodSpec:
    securityContext:
      runAsUser: 100
      runAsGroup: 1000
      fsGroup: 1000

  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" { capabilities = ["create", "read", "update", "delete", "list"] }