apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault
spec:
  size: 2
  image: hashicorp/vault:1.15.2

  # Service Account
  serviceAccount: vault

  # Azure Webhook Label
  vaultLabels:
    azure.workload.identity/use: "true"

  # Azure Unseal
  unsealConfig:
    azure:
      keyVaultName: "kv-calcifer-westeurope"

  # Physical Storage
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "local-path"
        resources:
          requests:
            storage: 5Gi

  #Mount Storage
  vaultContainerSpec:
    name: vault
    env:
      - name: SKIP_SETCAP
        value: "true"
      - name: SKIP_CHOWN
        value: "true"
    args: ["server", "-config=/vault/config/vault.json"]
    volumeMounts:
      - name: data
        mountPath: /vault/data
      - name: vault-config
        mountPath: /vault/config
    readinessProbe:
      exec:
        command: ["/bin/sh", "-c", "VAULT_ADDR=http://127.0.0.1:8200 vault status"]
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      exec:
        command: ["/bin/sh", "-c", "VAULT_ADDR=http://127.0.0.1:8200 vault status"]
      initialDelaySeconds: 30
      periodSeconds: 20

  # internal config (No explicit listener block here to avoid operator duplication)
  config:
    storage:
      raft:
        path: "/vault/data"
    ui: true
    disable_mlock: true
    api_addr: "http://vault.vault:8200"
    cluster_addr: "http://vault-0.vault-internal:8201"

  vaultPodSpec:
    securityContext:
      runAsUser: 100
      runAsGroup: 1000
      fsGroup: 1000

  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" { capabilities = ["create", "read", "update", "delete", "list"] }
