apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:IPDkiYjnug3B,iv:lE1yQY4kkIp9hRoWNyfh1e2kDoEe0bAO/hLVvdvHLF0=,tag:kUssEr8RXqZlIURcP7m8lA==,type:str]
    password: ENC[AES256_GCM,data:0xvTYCps5gm0m+Iqk6+WkHa28+vmkNFMTw==,iv:82GctB87rjSjq1/78swlkh74NyKBGCb53ls944GhPRs=,tag:GtrnvuAHIsW/RBXRkQZYRg==,type:str]
sops:
    age:
        - recipient: age1krtqjq3s9tqg3x6w02r60epx2pfyg9yer49vy05g4vanqatar5aqc7n87j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TG1GbjUwVVoyb3ZONXE0
            T2J3MkNjTmZGOTliOGxwelJrZlc3UTByV1hJClF2UVRmTy95b1h5b1BRbGlucU9i
            TWYzSzF2NEl4bTNZWDkwV2t2ODJvYkEKLS0tIGNMWUIvRmo0YzZ2c2NIeitrMmVy
            WHhPbk5BTG1DTENLSHhSN2JYQmkzV2cKiD0+/hywA9lpOUbrtU6RSfcv8zR4SYyU
            objCDk9R7z9k8WFYlTxH3y6J/RHg9gSEmLWYzPdadYUJof8P7nv8dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T20:40:44Z"
    mac: ENC[AES256_GCM,data:83FBvJ3mNfcPTLL5iWauGwKUzwZ+UuM9dgZrc28Wxpv+ITyP/fqQoW1kSo94QLDKAK/peZT2VDZIZqOLY4BKOBOkXwdVPYlKvZzMXlm0m/Ys9qcD1eTQIisf+GQtRZ7hGk3lU788xzTSzMtGP5u1yDI0eG8UvLVfPQ1mi947BY0=,iv:VpCD7aORqUpqxV06FTEODceXkWnQtL/ekOOYhXAITF0=,tag:AHoHgVZd4OpSJNIGvOPw1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
